#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.


menuentry 'ISO ARCH' {
  insmod search_fs_uuid
  search --no-floppy --set=isopart --fs-uuid 8AD0-8EF2
  set isofile='/iso/anarchy-1.0.0-x86_64.iso'
  set imgdevpath="/dev/disk/by-uuid/8AD0-8EF2"
  loopback loop ($isopart)$isofile
  linux (loop)/arch/boot/x86_64/vmlinuz archisodevice=/dev/loop0 img_dev=$imgdevpath img_loop=$isofile earlymodules=loop
  initrd (loop)/arch/boot/x86_64/archiso.img
}